# Generated by Django 2.2.5 on 2019-12-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambasBlog_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('MEX', 'México'), ('USA', 'Estados Unidos'), ('CAN', 'Canadá')], max_length=2),
        ),
    ]
