# Generated by Django 2.2.5 on 2019-12-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cambasBlog_users', '0003_auto_20191225_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
