# Generated by Django 2.2.5 on 2019-12-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cambasBlog_core', '0001_initial'),
        ('cambasBlog_users', '0004_remove_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='cambasBlog_core.Country'),
        ),
    ]
